In [1]:
project_dir = '../../'
import sys
sys.path.append(project_dir + 'NN/')
import numpy as np
import utils.preprocessing as pp

## Explain the k-fold algorithm strategy

In [2]:
data_test = np.arange(16).reshape((8, 2))
print('Example of dataset')
print(data_test)

Example of dataset
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [7]:
data, val = pp.split(data_test, kind = 'k-fold', k = 4)
print('First element returned is just the dataset (eventually reshuffled):')
print(data)
#print('\nThe second element returned is a list of tuple containing 2 index:')
print(val)

First element returned is just the dataset (eventually reshuffled):
[[ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[0 1]
 [2 3]]


In [7]:
print('In order to extract the fold (needed during the training) we can use:')
for i, (idx1, idx2) in enumerate(idxs):
    print(f'\nFold {i}')
    print('Train dataset:')
    training = np.delete(data, slice(idx1, idx2), axis = 0)
    print(training)
    print('Validation dataset:')
    validation = data[idx1:idx2]
    print(validation)
    print('Do the train and validation stuff...')

In order to extract the fold (needed during the training) we can use:


NameError: name 'idxs' is not defined