In [3]:
project_dir = '../../'
import sys
sys.path.append(project_dir + 'NN/')
import numpy as np
import utils.preprocessing as pp

## Explain the k-fold algorithm strategy

In [7]:
data_test = np.arange(20).reshape((10, 2))
print('Example of dataset')
print(data_test)

Example of dataset
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [13]:
data, idxs = pp.split(data_test, kind = 'k-fold', shuffle = False, k = 3)
print('First element returned is just the dataset (eventually reshuffled):')
print(data)
print('\nThe second element returned is a list of tuple containing 2 index:')
print(idxs)

First element returned is just the dataset (eventually reshuffled):
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

The second element returned is a list of tuple containing 2 index:
[(0, 3), (3, 6), (6, 10)]


In [17]:
print('In order to extract the fold (needed during the training) we can use:')
for i, (idx1, idx2) in enumerate(idxs):
    print(f'\nFold {i}')
    print('Train dataset:')
    training = np.delete(data, slice(idx1, idx2), axis = 0)
    print(training)
    print('Validation dataset:')
    validation = data[idx1:idx2]
    print(validation)
    print('Do the train and validation stuff...')

In order to extract the fold (needed during the training) we can use:

Fold 0
Train dataset:
[[ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
Validation dataset:
[[0 1]
 [2 3]
 [4 5]]
Do the train and validation stuff...

Fold 1
Train dataset:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
Validation dataset:
[[ 6  7]
 [ 8  9]
 [10 11]]
Do the train and validation stuff...

Fold 2
Train dataset:
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
Validation dataset:
[[12 13]
 [14 15]
 [16 17]
 [18 19]]
Do the train and validation stuff...
